/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HOME
 */
import javax.swing.*;
public class MainDash extends javax.swing.JFrame {

    /**
     * Creates new form MainDash
     */
    public MainDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtongotoStudentDash = new javax.swing.JButton();
        ButtongotoTeacherDash = new javax.swing.JButton();
        ButtongotoEXOdash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ButtongotoStudentDash.setBackground(new java.awt.Color(204, 204, 255));
        ButtongotoStudentDash.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ButtongotoStudentDash.setForeground(new java.awt.Color(0, 153, 153));
        ButtongotoStudentDash.setText("STUDENT");
        ButtongotoStudentDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtongotoStudentDashActionPerformed(evt);
            }
        });

        ButtongotoTeacherDash.setBackground(new java.awt.Color(204, 204, 255));
        ButtongotoTeacherDash.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ButtongotoTeacherDash.setForeground(new java.awt.Color(0, 153, 153));
        ButtongotoTeacherDash.setText("TEACHER");
        ButtongotoTeacherDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtongotoTeacherDashActionPerformed(evt);
            }
        });

        ButtongotoEXOdash.setBackground(new java.awt.Color(204, 204, 255));
        ButtongotoEXOdash.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ButtongotoEXOdash.setForeground(new java.awt.Color(0, 153, 153));
        ButtongotoEXOdash.setText("EXAM OFFICER");
        ButtongotoEXOdash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtongotoEXOdashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(ButtongotoStudentDash, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(ButtongotoTeacherDash, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(ButtongotoEXOdash, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtongotoStudentDash, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtongotoTeacherDash, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtongotoEXOdash, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtongotoEXOdashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtongotoEXOdashActionPerformed
        // TODO add your handling code here:
        EXOloginPage exologin = new EXOloginPage();
        exologin.setVisible(true);
        // Ensure closing this login page window does not close the main dashboard
        exologin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ButtongotoEXOdashActionPerformed

    private void ButtongotoTeacherDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtongotoTeacherDashActionPerformed
        // TODO add your handling code here:
        TeacherloginPage tlogin = new TeacherloginPage();
        tlogin.setVisible(true);
        // Ensure closing this login page window does not close the main dashboard:
        tlogin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ButtongotoTeacherDashActionPerformed

    private void ButtongotoStudentDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtongotoStudentDashActionPerformed
        // TODO add your handling code here:
        StudentloginPage studentLogin = new StudentloginPage();
        studentLogin.setVisible(true);
        // Ensure closing this login page window does not close the main dashboard:
        studentLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ButtongotoStudentDashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDash().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtongotoEXOdash;
    public javax.swing.JButton ButtongotoStudentDash;
    public javax.swing.JButton ButtongotoTeacherDash;
    // End of variables declaration//GEN-END:variables
}
